FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y git python3 build-essential gcc-arm-none-eabi
RUN git clone https://github.com/mettz/learning_to_fly_controller.git /controller && echo bump_2
WORKDIR /controller
RUN git submodule update --init --recursive -- external/crazyflie-firmware
RUN git submodule update --init -- external/rl_tools # non-recursive because we only need the headers
WORKDIR /controller/external/crazyflie-firmware
RUN make cf2_defconfig
WORKDIR /controller
CMD ["bash", "-c", "make -j$(nproc) && cp build/cf2.bin /output/cf2.bin"]
